version: '3'
services:

  eureka-serviceregistry:
    build: ./eureka
    ports:
     - "8761:8761"
    tty: true
  
  advert-service:
    build: ./Microservices/advertservice
    ports:
    - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
  
  auth-service:
    build:  ./Microservices/auth
    ports:
    - "8082:8082"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  rent-service:
    build:  ./Microservices/rentservice
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  search-service:
    build:  ./Microservices/searchservice
    ports:
    - "8084:8084"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  zuul:
    build: ./zuul
    ports:
    - "8089:8089"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - advert-service
      - auth-service
      - rent-service
      - search-service


  

  
